<x-layouts.admin :title="$mode === 'create' ? 'Tambah Barang Inventory' : 'Edit Barang Inventory'">
    <div class="admin-compact space-y-4">
        @include('admin.inventory.partials.header', ['icon' => 'package', 'title' => $mode === 'create' ? 'Tambah Barang' : 'Edit Barang', 'description' => 'Stok hanya berubah melalui transaksi yang tercatat.'])
        @if(session('success'))<div class="rounded-lg bg-emerald-50 p-3 text-emerald-700">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-lg bg-rose-50 p-3 text-rose-700">{{ $errors->first() }}</div>@endif
        <form method="POST" enctype="multipart/form-data" action="{{ $mode === 'create' ? route('admin.inventory.items.store') : route('admin.inventory.items.update', $item) }}" class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            @csrf @if($mode === 'edit') @method('PUT') @endif
            <div class="grid gap-4 md:grid-cols-2">
                @foreach ([['uid','UID','text'],['name','Nama Barang','text'],['type_category','Tipe Kategori','text'],['size','Ukuran','text'],['unit','Satuan','text'],['minimum_stock','Stok Minimum','number']] as [$name,$label,$type])<label class="text-sm font-semibold text-slate-700">{{ $label }}<input type="{{ $type }}" name="{{ $name }}" value="{{ old($name, $item->$name) }}" @if($type==='number') min="0" step="1" inputmode="numeric" @endif class="mt-1 w-full rounded-lg border-slate-300" @required(in_array($name,['uid','name','unit','minimum_stock']))></label>@endforeach
                <label class="text-sm font-semibold">Jenis<select name="item_type" class="mt-1 w-full rounded-lg border-slate-300"><option value="consumable" @selected(old('item_type',$item->item_type)==='consumable')>Consumable</option><option value="equipment" @selected(old('item_type',$item->item_type)==='equipment')>Peralatan</option></select></label>
                <label class="text-sm font-semibold">Kategori<select name="inventory_category_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">-</option>@foreach($categories as $row)<option value="{{ $row->id }}" @selected((string)old('inventory_category_id',$item->inventory_category_id)===(string)$row->id)>{{ $row->name }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold">Subkategori<select name="inventory_subcategory_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">-</option>@foreach($subcategories as $row)<option value="{{ $row->id }}" @selected((string)old('inventory_subcategory_id',$item->inventory_subcategory_id)===(string)$row->id)>{{ $row->category?->name }} · {{ $row->name }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold">Lokasi<select name="inventory_location_id" class="mt-1 w-full rounded-lg border-slate-300"><option value="">-</option>@foreach($locations as $row)<option value="{{ $row->id }}" @selected((string)old('inventory_location_id',$item->inventory_location_id)===(string)$row->id)>{{ $row->code }} · {{ $row->name }}</option>@endforeach</select></label>
                @if($mode==='create')<label class="text-sm font-semibold">Opening Stock<input type="number" name="opening_stock" value="{{ old('opening_stock',0) }}" min="0" step="1" inputmode="numeric" class="mt-1 w-full rounded-lg border-slate-300"></label>@else<label class="text-sm font-semibold">Stok Saat Ini<input value="{{ number_format((int)$item->current_stock,0,',','.') }} {{ $item->unit }}" readonly class="mt-1 w-full rounded-lg border-slate-300 bg-slate-50"></label>@endif
                <label class="text-sm font-semibold">Gambar<input type="file" name="image" accept=".jpg,.jpeg,.png,.webp" class="mt-1 block w-full rounded-lg border border-slate-300 p-2"></label>
                <label class="flex items-center gap-2 text-sm font-semibold"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$item->is_active))> Aktif</label>
                @if($mode==='edit')<input type="hidden" name="remove_image" value="0">@if($item->image_path)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="remove_image" value="1"> Hapus gambar saat ini</label>@endif @endif
                <label class="text-sm font-semibold md:col-span-2">Deskripsi<textarea name="description" rows="3" class="mt-1 w-full rounded-lg border-slate-300">{{ old('description',$item->description) }}</textarea></label>
            </div>
            <div class="mt-5 flex justify-end gap-2"><a href="{{ route('admin.inventory.items.index') }}" class="rounded-lg border px-4 py-2 font-semibold">Kembali</a><button class="rounded-lg bg-blue-600 px-4 py-2 font-semibold text-white">Simpan</button></div>
        </form>
    </div>
</x-layouts.admin>
