<x-layouts.admin title="Master Barang Inventory">
    <div class="admin-compact space-y-4">
        @include('admin.inventory.partials.header', ['icon' => 'package-search', 'title' => 'Master Barang', 'description' => 'Daftar consumable dan peralatan gudang.'])
        @if (session('success'))<div class="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
        @if ($errors->any())<div class="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{{ $errors->first() }}</div>@endif
        <div class="flex justify-end"><a href="{{ route('admin.inventory.items.create') }}" class="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white"><i data-lucide="plus" class="h-4 w-4"></i> Tambah Barang</a></div>
        <form method="GET" class="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-6">
            <input name="search" value="{{ request('search') }}" placeholder="Cari UID atau nama barang" class="rounded-lg border-slate-300 md:col-span-2">
            <select name="item_type" class="rounded-lg border-slate-300"><option value="">Semua jenis</option><option value="consumable" @selected(request('item_type') === 'consumable')>Consumable</option><option value="equipment" @selected(request('item_type') === 'equipment')>Peralatan</option></select>
            <select name="status" class="rounded-lg border-slate-300"><option value="">Semua status</option>@foreach (['active'=>'Aktif','inactive'=>'Nonaktif','low'=>'Stok menipis','out'=>'Stok habis','archived'=>'Arsip'] as $value=>$label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select>
            <select name="category" class="rounded-lg border-slate-300"><option value="">Semua kategori</option>@foreach ($categories as $category)<option value="{{ $category->id }}" @selected((string) request('category') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select>
            <button class="rounded-lg bg-slate-800 px-4 py-2 font-semibold text-white">Filter</button>
        </form>
        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm">
            <thead class="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th class="px-3 py-3">Foto</th><th class="px-3 py-3">UID</th><th class="px-3 py-3">Nama</th><th class="px-3 py-3">Jenis</th><th class="px-3 py-3">Lokasi</th><th class="px-3 py-3 text-right">Stok</th><th class="px-3 py-3 text-right">Minimum</th><th class="px-3 py-3">Status</th><th class="px-3 py-3">Aksi</th></tr></thead>
            <tbody class="divide-y divide-slate-100">@forelse ($items as $item)
                @php($archived = $item->trashed())
                <tr><td class="px-3 py-3">@if($item->image_path && !$archived)<img src="{{ route('admin.inventory.items.image', $item) }}" class="h-10 w-10 rounded object-cover" alt="">@else<span class="inline-flex h-10 w-10 items-center justify-center rounded bg-slate-100"><i data-lucide="image" class="h-4 w-4 text-slate-400"></i></span>@endif</td>
                <td class="px-3 py-3 font-semibold">{{ $item->uid }}</td><td class="px-3 py-3"><div class="font-semibold">{{ $item->name }}</div><div class="text-xs text-slate-500">{{ $item->category?->name }}</div></td><td class="px-3 py-3">{{ $item->item_type === 'equipment' ? 'Peralatan' : 'Consumable' }}</td><td class="px-3 py-3">{{ $item->location?->code ?? '-' }}</td><td class="px-3 py-3 text-right font-bold">{{ number_format((int) $item->current_stock, 0, ',', '.') }} {{ $item->unit }}</td><td class="px-3 py-3 text-right">{{ number_format((int) $item->minimum_stock, 0, ',', '.') }}</td><td class="px-3 py-3">{{ $archived ? 'Arsip' : ($item->is_active ? 'Aktif' : 'Nonaktif') }}</td>
                <td class="px-3 py-3"><div class="flex gap-1">@if($archived)<form method="POST" action="{{ route('admin.inventory.items.restore', $item->id) }}">@csrf<button class="rounded bg-emerald-50 px-2 py-1 font-semibold text-emerald-700">Restore</button></form>@else<a href="{{ route('admin.inventory.items.edit', $item) }}" class="rounded bg-slate-100 px-2 py-1 font-semibold">Edit</a>@if($item->is_active)<a href="{{ route('admin.inventory.stock-in.create', ['item_id'=>$item->id]) }}" class="rounded bg-blue-50 px-2 py-1 font-semibold text-blue-700">Tambah Stok</a>@endif<form method="POST" action="{{ route('admin.inventory.items.destroy', $item) }}">@csrf @method('DELETE')<button class="rounded bg-rose-50 px-2 py-1 font-semibold text-rose-700">Arsip</button></form>@endif</div></td></tr>
            @empty<tr><td colspan="9" class="px-4 py-8 text-center text-slate-500">Belum ada master barang.</td></tr>@endforelse</tbody>
        </table></div><div class="border-t px-4 py-3">{{ $items->links() }}</div></section>
    </div>
</x-layouts.admin>
